### PR TITLE
Changes to support single nfp ini file

### PR DESCRIPTION
**Pull request by DhuldevValekar**
Changes to support single nfp ini file.

### CODE REVIEW

**Comment by DhuldevValekar** [comment]
@snaiksat @amittbose

**Comment by snaiksat** [comment]
Could you point me to this file in the GBP source tree?

**Comment by DhuldevValekar** [comment]
nfp.ini file is in following location.
https://review.openstack.org/#/c/359883/8/gbpservice/nfp/bin/nfp.ini

**Comment by snaiksat** [comment]
In that case I think we would at least need to wait for that patch to merge. In the future, please mention such dependencies in the commit message. It will make it easier to review the pull request.

**Comment by njagadish** [comment]
@snaiksat - Following is the latest file. This got merged now. Could you please merge this change now.

https://review.openstack.org/#/c/359883/81/gbpservice/nfp/bin/nfp.ini

**Comment by njagadish** [comment]
@amittbose

**Comment by amittbose** [comment]
Can you create pull request for merge to 'master'? This one looks to be for 'liberty'. Also, I don't think the NFP changes have been backported to GBP branch for liberty, please ensure that happens before updating the spec files for liberty.

**Comment by DhuldevValekar** [comment]
Hi Amit,

updated PR with your comments is,
https://github.com/group-policy/gbp-packages/pull/2

**Pull request merged**
